package agent

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"testing"

	"github.com/jonahgcarpenter/oswald-ai/internal/config"
	"github.com/jonahgcarpenter/oswald-ai/internal/llm"
	"github.com/jonahgcarpenter/oswald-ai/internal/media"
	"github.com/jonahgcarpenter/oswald-ai/internal/memory"
	"github.com/jonahgcarpenter/oswald-ai/internal/shared/requestctx"
	"github.com/jonahgcarpenter/oswald-ai/internal/tools/governance"
	toolnames "github.com/jonahgcarpenter/oswald-ai/internal/tools/names"
	"github.com/jonahgcarpenter/oswald-ai/internal/tools/registry"
)

func TestGeneratedImagesFeedSuccessiveTextOnlyEdits(t *testing.T) {
	for _, streaming := range []bool{false, true} {
		t.Run(fmt.Sprint(streaming), func(t *testing.T) {
			chat := &fakeChatter{}
			reg := registry.New(config.NewLogger(config.LevelError))
			a, store := newTestAgent(t, chat, nil, reg)
			var logs bytes.Buffer
			level := config.LevelInfo
			if streaming {
				level = config.LevelDebug
			}
			a.log = config.NewLogger(level)
			a.log.SetOutput(&logs)
			var previous string
			count := 0
			handler := func(ctx context.Context, args map[string]interface{}) (governance.Result, error) {
				sources := requestctx.InputImagesFromContext(ctx)
				if count > 0 && (len(sources) == 0 || sources[0].Data != previous) {
					t.Fatal("edit did not receive preceding generated bytes")
				}
				image := testInputImage(t, 2+count, 3+count)
				data, err := base64.StdEncoding.DecodeString(image.Data)
				if err != nil {
					t.Fatal(err)
				}
				normalized, err := media.NormalizeInputImageFromBytes(nil, image.MimeType, data, "generated")
				if err != nil {
					t.Fatal(err)
				}
				previous = normalized.Image.Data
				count++
				return governance.Result{Content: `{"status":"generated"}`, Outcome: governance.OutcomeProductive, Attachments: []media.OutputAttachment{{Filename: fmt.Sprintf("image-%d.jpg", count), MIMEType: image.MimeType, Data: data}}}, nil
			}
			policy := testToolPolicy()
			policy.History.Mode = governance.HistoryMetadata
			for _, name := range []string{toolnames.ComfyUITextToImage, toolnames.ComfyUIImageToImage} {
				if err := registerTestTool(t, reg, registry.Spec{Name: name, Description: name}, policy, handler); err != nil {
					t.Fatal(err)
				}
			}
			for i, prompt := range []string{"generate a car", "make it blue", "make it purple"} {
				name := toolnames.ComfyUIImageToImage
				if i == 0 {
					name = toolnames.ComfyUITextToImage
				}
				chat.responses = append(chat.responses, &llm.ChatResponse{Message: llm.ChatMessage{Role: "assistant", ToolCalls: []llm.ToolCall{{ID: "generate", Function: llm.ToolFunction{Name: name, Arguments: map[string]interface{}{"prompt": prompt}}}}}}, &llm.ChatResponse{Message: llm.ChatMessage{Role: "assistant", Content: "Here it is."}})
				var callback func(StreamChunk)
				if streaming {
					callback = func(StreamChunk) {}
				}
				response, err := processAgent(a, fmt.Sprintf("request-%d", i), "discord", "session", "user-1", "User", prompt, nil, callback)
				if err != nil || response.SourceTurnID == 0 {
					t.Fatalf("response persisted=%v err=%v", response != nil, err)
				}
				final := chat.requests[len(chat.requests)-1]
				if final.Stream != streaming {
					t.Fatal("stream setting changed")
				}
				last := final.Messages[len(final.Messages)-1]
				if len(last.Images) != 1 || last.Images[0].Data != previous || !strings.Contains(last.Content, "Generated image shown:") {
					t.Fatal("final model call did not see normalized output")
				}
				assets, err := store.SessionImages(context.Background(), "user-1", "session", response.SessionGeneration)
				if err != nil || len(assets) != i+1 || assets[0].Data != previous {
					t.Fatalf("retained images=%d err=%v", len(assets), err)
				}
				turns, err := store.RecentSessionTurns("user-1", "session", response.SessionGeneration, 10)
				if err != nil {
					t.Fatal(err)
				}
				encoded, _ := json.Marshal(turns)
				if strings.Contains(string(encoded), previous) {
					t.Fatal("base64 leaked into durable turn or tool history")
				}
				if strings.Contains(logs.String(), previous) || strings.Contains(logs.String(), prompt) || strings.Contains(logs.String(), assets[0].ID) {
					t.Fatal("private image data leaked into logs")
				}
			}
			for _, event := range []string{"agent.images.loaded", "agent.images.generated", "agent.images.stored"} {
				if strings.Count(logs.String(), `"event":"`+event+`"`) != 3 {
					t.Fatalf("wrong emission count for %s", event)
				}
			}
		})
	}
}

func TestGeneratedImageContextSurvivesCompaction(t *testing.T) {
	compactor := &fakeForegroundCompactor{artifact: memory.SummaryArtifact{Narrative: "Generated an image."}}
	state := newForegroundCompactionState(compactor, 100, "policy", "", "edit it", nil, nil, []memory.SessionTurn{{ID: 1, UserText: "old", AssistantText: "answer"}}, nil)
	image := requestctx.InputImage{ID: "opaque-id", MIMEType: "image/png", Data: "image-payload", Source: "generated"}
	message := sessionImageContext([]requestctx.InputImage{image}, []requestctx.InputImage{image})
	state.imageContext = &message
	rebuilt, stats, err := state.prepare(context.Background(), []llm.ChatMessage{message}, nil, true)
	if err != nil || !stats.Compacted {
		t.Fatalf("compacted=%v err=%v", stats.Compacted, err)
	}
	last := rebuilt[len(rebuilt)-1]
	if len(last.Images) != 1 || last.Images[0].Data != image.Data || !strings.Contains(last.Content, image.ID) {
		t.Fatal("compaction lost active image")
	}
	encoded, _ := json.Marshal(compactor.calls)
	if strings.Contains(string(encoded), image.Data) {
		t.Fatal("image bytes entered compaction debt")
	}
}

func TestGeneratedImagesChainWithinBatchAndReachToolsDisabledFinal(t *testing.T) {
	chat := &fakeChatter{}
	reg := registry.New(config.NewLogger(config.LevelError))
	a, store := newTestAgent(t, chat, nil, reg)
	a.toolPolicy = governance.GlobalPolicy{MaxExecutions: 6, MaxToolIterations: 10}
	current := testInputImage(t, 2, 3)
	previous := current.Data
	count := 0
	policy := testToolPolicy()
	policy.MaxExecutions = 0
	policy.History.Mode = governance.HistoryMetadata
	err := registerTestTool(t, reg, registry.Spec{Name: toolnames.ComfyUIImageToImage, Description: "edit"}, policy, func(ctx context.Context, args map[string]interface{}) (governance.Result, error) {
		sources := requestctx.InputImagesFromContext(ctx)
		if len(sources) == 0 || sources[0].Data != previous {
			t.Fatal("default source did not advance within batch")
		}
		if count == 0 && sources[0].ID != "current-1" {
			t.Fatal("current image has no selector")
		}
		image := testInputImage(t, 3+count, 4+count)
		data, _ := base64.StdEncoding.DecodeString(image.Data)
		normalized, err := media.NormalizeInputImageFromBytes(nil, image.MimeType, data, "generated")
		if err != nil {
			t.Fatal(err)
		}
		previous = normalized.Image.Data
		count++
		return governance.Result{Content: `{"status":"generated"}`, Outcome: governance.OutcomeProductive, Attachments: []media.OutputAttachment{{Filename: fmt.Sprintf("image-%d.jpg", count), MIMEType: image.MimeType, Data: data}}}, nil
	})
	if err != nil {
		t.Fatal(err)
	}
	var calls []llm.ToolCall
	for i := 0; i < 6; i++ {
		calls = append(calls, llm.ToolCall{ID: fmt.Sprint(i), Function: llm.ToolFunction{Name: toolnames.ComfyUIImageToImage, Arguments: map[string]interface{}{"prompt": fmt.Sprintf("edit %d", i)}}})
	}
	chat.responses = []*llm.ChatResponse{{Message: llm.ChatMessage{Role: "assistant", ToolCalls: calls}}, {Message: llm.ChatMessage{Role: "assistant", Content: "Final image."}}}
	response, err := processAgent(a, "batch", "discord", "session", "user-1", "User", "edit repeatedly", []llm.InputImage{current}, nil)
	if err != nil || response == nil || count != 6 {
		t.Fatalf("count=%d err=%v", count, err)
	}
	final := chat.requests[len(chat.requests)-1]
	if len(final.Tools) != 0 {
		t.Fatal("final tools not disabled")
	}
	last := final.Messages[len(final.Messages)-1]
	if len(last.Images) != 4 || last.Images[3].Data != previous {
		t.Fatal("latest four generated outputs not retained")
	}
	results := 0
	for _, message := range final.Messages {
		if message.Role == "tool" {
			results++
		}
	}
	if results != 6 {
		t.Fatalf("correlated tool results=%d", results)
	}
	assets, err := store.SessionImages(context.Background(), "user-1", "session", response.SessionGeneration)
	if err != nil || len(assets) != 4 || assets[0].Data != previous {
		t.Fatalf("assets=%d err=%v", len(assets), err)
	}
}

func TestGeneratedImageCannotSucceedAfterSessionResetBeforePersistence(t *testing.T) {
	chat := &fakeChatter{responses: []*llm.ChatResponse{toolCallResponse("generate", toolnames.ComfyUITextToImage, nil), {Message: llm.ChatMessage{Role: "assistant", Content: "Here it is."}}}}
	reg := registry.New(config.NewLogger(config.LevelError))
	a, store := newTestAgent(t, chat, nil, reg)
	image := testInputImage(t, 2, 3)
	data, _ := base64.StdEncoding.DecodeString(image.Data)
	if err := registerTestTool(t, reg, registry.Spec{Name: toolnames.ComfyUITextToImage, Description: "generate"}, testToolPolicy(), func(ctx context.Context, _ map[string]interface{}) (governance.Result, error) {
		if err := store.ResetSessionContext(ctx, "user-1", "session"); err != nil {
			t.Fatal(err)
		}
		return governance.Result{Content: `{"status":"generated"}`, Outcome: governance.OutcomeProductive, Attachments: []media.OutputAttachment{{Filename: "output.jpg", MIMEType: image.MimeType, Data: data}}}, nil
	}); err != nil {
		t.Fatal(err)
	}
	response, err := processAgent(a, "reset", "discord", "session", "user-1", "User", "generate", nil, nil)
	if err == nil || response != nil {
		t.Fatal("unpersisted generated image reported as delivered")
	}
	var count int
	if err := store.sql.QueryRow(`SELECT COUNT(*) FROM session_images`).Scan(&count); err != nil || count != 0 {
		t.Fatalf("unfenced images=%d err=%v", count, err)
	}
}
